# Generated by Django 5.2.11 on 2026-08-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=15, null=True, unique=True
            ),
        ),
    ]
