# Generated by Django 5.2.11 on 2026-08-13 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Iranian mobile number (e.g. 09123456789).",
                        regex="^(\\+98|0098|0)?9\\d{9}$",
                    )
                ],
            ),
        ),
    ]
