# Generated by Django 5.2.11 on 2026-08-13 10:45
#
# Data migration: backfill User.phone_number (Task 2.1.1.1/2.1.1.2) from
# the legacy, unvalidated Profile.phone_number free-text field, so users
# who already gave a phone number via the old ProfileView PATCH flow
# don't have to re-enter it now that phone lives on User.
#
# NOTE ON DUPLICATED NORMALIZATION LOGIC:
# This intentionally duplicates the regex/normalization logic from
# accounts/validators.py (normalize_iranian_phone / iranian_phone_regex)
# instead of importing it. No other migration in this project imports
# app code directly (checked accounts/migrations/0001-0003 and every
# other app's migrations — none do), and it's a well-known Django
# anti-pattern for data migrations specifically: app code can change or
# be deleted in the future, but a migration must keep working exactly as
# written against whatever the schema looked like *at the time it ran*.
# Models are accessed via the historical model API (apps.get_model)
# for the same reason.

import re

from django.db import migrations

_PREFIX_RE = re.compile(r"^(\+98|0098|0)?(9\d{9})$")


def _normalize_iranian_phone_or_none(value):
    """
    Migration-local copy of accounts.validators.normalize_iranian_phone,
    returning None instead of raising on invalid input (simpler for a
    skip-and-log backfill loop than try/except at every call site).
    """
    if not value:
        return None
    match = _PREFIX_RE.match(value.strip())
    if not match:
        return None
    return f"0{match.group(2)}"


def backfill_user_phone_from_profile(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    User = apps.get_model("accounts", "User")

    skipped_invalid = 0
    skipped_duplicate = 0
    migrated = 0

    profiles = (
        Profile.objects.exclude(phone_number__isnull=True)
        .exclude(phone_number__exact="")
        .select_related("user")
    )

    for profile in profiles:
        normalized = _normalize_iranian_phone_or_none(profile.phone_number)

        if normalized is None:
            skipped_invalid += 1
            print(
                f"[backfill_user_phone_from_profile] Skipping profile "
                f"id={profile.pk} (user_id={profile.user_id}): "
                f"phone_number={profile.phone_number!r} does not match "
                f"the expected Iranian mobile format."
            )
            continue

        # Respect the unique constraint on User.phone_number: if another
        # user already has this normalized number, don't overwrite it or
        # crash the migration — just skip and log for manual follow-up.
        already_taken = (
            User.objects.filter(phone_number=normalized)
            .exclude(pk=profile.user_id)
            .exists()
        )
        if already_taken:
            skipped_duplicate += 1
            print(
                f"[backfill_user_phone_from_profile] Skipping profile "
                f"id={profile.pk} (user_id={profile.user_id}): "
                f"normalized phone_number={normalized!r} is already set "
                f"on a different user."
            )
            continue

        User.objects.filter(pk=profile.user_id).update(phone_number=normalized)
        migrated += 1

    print(
        f"[backfill_user_phone_from_profile] Done. "
        f"migrated={migrated} skipped_invalid={skipped_invalid} "
        f"skipped_duplicate={skipped_duplicate}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RunPython(
            backfill_user_phone_from_profile,
            # Reverse is a no-op: this is a one-way backfill copying data
            # that already exists on Profile into User. There's nothing
            # meaningful to "undo" — User.phone_number would just be
            # cleared, but the source data on Profile.phone_number is
            # untouched by the forward migration anyway (Task 2.1.1.3
            # handles reconciling/removing the legacy field later), so a
            # reverse here would only destroy newly-set User data without
            # restoring any prior state worth restoring.
            reverse_code=migrations.RunPython.noop,
        ),
    ]
