# Generated by Django 5.2.11 on 2026-08-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_user_phone_from_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("register", "Register"),
                            ("reset", "Password Reset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_number", "purpose", "is_used"],
                        name="accounts_ot_phone_n_76ae90_idx",
                    )
                ],
            },
        ),
    ]
