# Generated by Django 5.2.11 on 2026-10-07 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cart_session_key_alter_cart_user_and_more"),
        ("promotions", "0002_couponredemption"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="promotions.coupon",
            ),
        ),
    ]
