# Generated by Django 5.2.11 on 2026-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("post", "Iran Post"),
                            ("tipax", "Tipax"),
                            ("snapbox", "SnapBox"),
                            ("alopeyk", "AloPeyk"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Carrier-specific settings (API base URL overrides, account IDs, etc.) NOT including secret API keys — those belong in environment variables, never in this DB-stored JSON field.",
                    ),
                ),
                (
                    "supports_same_day",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this carrier can offer same-day/local delivery (relevant for AloPeyk-style city-restricted couriers).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
    ]
