# Generated by Django 5.2.11 on 2026-09-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_seed_shipping_carriers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("alborz", "Alborz"),
                            ("ardabil", "Ardabil"),
                            ("bushehr", "Bushehr"),
                            ("chaharmahal_and_bakhtiari", "Chaharmahal and Bakhtiari"),
                            ("east_azerbaijan", "East Azerbaijan"),
                            ("fars", "Fars"),
                            ("gilan", "Gilan"),
                            ("golestan", "Golestan"),
                            ("hamadan", "Hamadan"),
                            ("hormozgan", "Hormozgan"),
                            ("ilam", "Ilam"),
                            ("isfahan", "Isfahan"),
                            ("kerman", "Kerman"),
                            ("kermanshah", "Kermanshah"),
                            ("khuzestan", "Khuzestan"),
                            (
                                "kohgiluyeh_and_boyer_ahmad",
                                "Kohgiluyeh and Boyer-Ahmad",
                            ),
                            ("kurdistan", "Kurdistan"),
                            ("lorestan", "Lorestan"),
                            ("markazi", "Markazi"),
                            ("mazandaran", "Mazandaran"),
                            ("north_khorasan", "North Khorasan"),
                            ("qazvin", "Qazvin"),
                            ("qom", "Qom"),
                            ("khorasan_razavi", "Khorasan Razavi"),
                            ("semnan", "Semnan"),
                            ("sistan_and_baluchestan", "Sistan and Baluchestan"),
                            ("south_khorasan", "South Khorasan"),
                            ("tehran", "Tehran"),
                            ("west_azerbaijan", "West Azerbaijan"),
                            ("yazd", "Yazd"),
                            ("zanjan", "Zanjan"),
                        ],
                        help_text="Destination province this rate applies to.",
                        max_length=30,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Optional: leave blank to apply to the whole province; set to override for a specific city (e.g. same-city rates for AloPeyk).",
                        max_length=100,
                    ),
                ),
                ("min_weight_g", models.PositiveIntegerField(default=0)),
                (
                    "max_weight_g",
                    models.PositiveIntegerField(
                        help_text="Upper bound of this weight bracket, in grams."
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_days_min", models.PositiveSmallIntegerField(default=1)),
                ("estimated_days_max", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingcarrier",
                    ),
                ),
            ],
            options={
                "ordering": ["carrier", "province", "min_weight_g"],
                "indexes": [
                    models.Index(
                        fields=["carrier", "province", "city"],
                        name="shipping_sh_carrier_279652_idx",
                    )
                ],
            },
        ),
    ]
