# Generated by Django 5.2.11 on 2026-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
