# Generated by Django 5.2.11 on 2026-08-11 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_review_is_verified_purchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "user")},
        ),
    ]
