# Generated by Django 5.2.11 on 2026-08-27 10:40

from django.db import migrations

# ─── Business decision: splitting stock across color variants ────────────────
# A pre-variant Product has a single `stock` integer. When a product has N
# related ProductColor rows, we must create N ProductVariant rows (one per
# color) but there is no historical per-color stock data to draw on — the
# split has to be *decided*, not derived.
#
# We deliberately EVENLY DIVIDE the existing stock across the N color
# variants (integer division, with the remainder — if `stock` doesn't divide
# evenly by N — added to the first variant) rather than either of the two
# alternatives:
#   - Putting the full stock on every variant would multiply total on-hand
#     inventory by N, silently inflating it system-wide.
#   - Putting the full stock on only the first variant and 0 on the rest
#     would make every color but one look completely out of stock the
#     moment this migration runs, which is a worse customer-facing outcome
#     than a merely imprecise split.
# Even division keeps total stock conserved (sum of variant stock == the
# original Product.stock) and avoids making any single color look
# artificially unavailable. It is still an approximation — real per-color
# stock will need manual/admin correction post-migration — but it's the
# safest default given the data we actually have.
LEGACY_SKU_PREFIX = "LEGACY-"


def migrate_products_to_variants(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    ProductColor = apps.get_model("shop", "ProductColor")
    ProductVariant = apps.get_model("shop", "ProductVariant")

    for product in Product.objects.all().iterator():
        product_colors = list(
            ProductColor.objects.filter(product=product).select_related("color")
        )

        if product_colors:
            # Distinct colors only — a product could (in theory) have
            # duplicate ProductColor rows pointing at the same color if a
            # unique_together constraint was ever bypassed; guard against
            # creating two variants for the same color.
            seen_color_ids = set()
            distinct_colors = []
            for pc in product_colors:
                if pc.color_id not in seen_color_ids:
                    seen_color_ids.add(pc.color_id)
                    distinct_colors.append(pc.color)

            n = len(distinct_colors)
            base_share, remainder = divmod(product.stock, n)

            variants = []
            for index, color in enumerate(distinct_colors):
                # Remainder (if stock doesn't divide evenly) goes to the
                # first variant so the total sums exactly to product.stock.
                variant_stock = base_share + remainder if index == 0 else base_share
                variants.append(
                    ProductVariant(
                        product=product,
                        sku=f"{LEGACY_SKU_PREFIX}{product.id}-{index}",
                        barcode="",
                        color=color,
                        price=product.price,
                        original_price=product.original_price,
                        stock=variant_stock,
                        is_active=True,
                    )
                )
            ProductVariant.objects.bulk_create(variants)
        else:
            # No color data at all — a single, colorless variant carrying
            # the full price/original_price/stock over unchanged.
            ProductVariant.objects.create(
                product=product,
                sku=f"{LEGACY_SKU_PREFIX}{product.id}-0",
                barcode="",
                color=None,
                price=product.price,
                original_price=product.original_price,
                stock=product.stock,
                is_active=True,
            )


def reverse_migrate_products_to_variants(apps, schema_editor):
    """
    Delete only the ProductVariant rows this migration created, identified
    by their `LEGACY-` SKU prefix. Any variants created afterwards by real
    usage of the variant system (e.g. via Task 3.1.2.1's SKU generation)
    will use a different SKU scheme and are left untouched.
    """
    ProductVariant = apps.get_model("shop", "ProductVariant")
    ProductVariant.objects.filter(sku__startswith=LEGACY_SKU_PREFIX).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productvariant"),
    ]

    operations = [
        migrations.RunPython(
            migrate_products_to_variants,
            reverse_migrate_products_to_variants,
        ),
    ]
