# Generated by Django 5.2.11 on 2026-08-30 19:52

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_migrate_products_to_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="EAN-13 barcode (13 digits with a valid check digit). Optional.",
                max_length=20,
                validators=[shop.validators.validate_ean13],
            ),
        ),
    ]
