# Generated by Django 5.2.11 on 2026-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_productvariant_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="skin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oily", "Oily"),
                    ("dry", "Dry"),
                    ("combination", "Combination"),
                    ("sensitive", "Sensitive"),
                    ("normal", "Normal"),
                    ("all", "All Skin Types"),
                ],
                max_length=20,
            ),
        ),
    ]
