# Generated by Django 5.2.11 on 2026-08-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_product_skin_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hair_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight", "Straight"),
                    ("wavy", "Wavy"),
                    ("curly", "Curly"),
                    ("coily", "Coily"),
                    ("all", "All Hair Types"),
                ],
                max_length=20,
            ),
        ),
    ]
