# Generated by Django 5.2.11 on 2026-08-31 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_hair_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="spf",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
