# Generated by Django 5.2.11 on 2026-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_spf"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="volume_ml",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_g",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
