# Generated by Django 5.2.11 on 2026-09-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_productvariant_volume_ml_productvariant_weight_g"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
    ]
