# Generated by Django 5.2.11 on 2026-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_product_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
