# Generated by Django 5.2.11 on 2026-09-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_product_country_of_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="manufacture_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
