# Generated by Django 5.2.11 on 2026-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_productvariant_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
