# Generated by Django 5.2.11 on 2026-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_productvariant_batch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="usage_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="warnings",
            field=models.TextField(blank=True),
        ),
    ]
