# Generated by Django 5.2.11 on 2026-09-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_product_usage_instructions_product_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("unisex", "Unisex"), ("female", "Female"), ("male", "Male")],
                default="unisex",
                max_length=10,
            ),
        ),
    ]
