# Generated by Django 5.2.11 on 2026-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_product_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_cruelty_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_organic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
    ]
