# Generated by Django 5.2.11 on 2026-09-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_product_is_cruelty_free_product_is_organic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="irc_regulatory_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
