# Generated by Django 5.2.11 on 2026-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_product_irc_regulatory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="regulatory_verified",
            field=models.BooleanField(default=False),
        ),
    ]
