# Generated by Django 5.2.11 on 2026-09-06 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_orderitem_variant_fields"),
        ("shop", "0020_product_regulatory_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("cancellation", "Order Cancellation"),
                            ("manual", "Manual Adjustment"),
                            ("restock", "Restock"),
                            ("expiry_sweep", "Expiry Deactivation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_delta",
                    models.IntegerField(
                        help_text="Positive for increases, negative for decreases."
                    ),
                ),
                (
                    "stock_after",
                    models.PositiveIntegerField(
                        help_text="Variant's stock value immediately after this movement."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who triggered this (manual adjustments only); null for system-triggered movements.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="order.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "-created_at"],
                        name="shop_stockm_variant_4d5e22_idx",
                    )
                ],
            },
        ),
    ]
