# Generated by Django 5.2.11 on 2026-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
