# Generated by Django 5.2.11 on 2026-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_couponredemption"),
        ("shop", "0024_seed_deactivate_expired_variants_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="If set, this coupon only applies to items in these categories. Leave empty to apply to all categories. Matching is exact: a product in a sub-category does NOT match its parent category, so select the sub-categories you want as well.",
                to="shop.category",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="If set, this coupon only applies to these specific products. Leave empty (with no category restriction either) to apply cart-wide.",
                to="shop.product",
            ),
        ),
    ]
