# Generated by Django 5.2.11 on 2026-08-29 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("shop", "0006_migrate_products_to_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shop.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_attributes_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_sku",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
