# Generated by Django 5.2.11 on 2026-09-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_orderitem_variant_fields"),
        ("shipping", "0003_shippingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingcarrier",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
