# Generated by Django 5.2.11 on 2026-09-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0002_orderitem_variant_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("zarinpal", "ZarinPal"),
                            ("zibal", "Zibal"),
                            ("idpay", "IDPay"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gateway-issued reference code for this transaction (ZarinPal calls this 'Authority').",
                        max_length=100,
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        help_text="Gateway-issued final transaction reference, populated on success.",
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "raw_callback_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Full raw payload received from the gateway's callback, stored for audit/debugging.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gateway", "authority"],
                        name="payments_pa_gateway_3f1f82_idx",
                    )
                ],
            },
        ),
    ]
