# Generated by Django 5.2.11 on 2026-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_gateway",
                    models.CharField(
                        choices=[
                            ("zarinpal", "ZarinPal"),
                            ("zibal", "Zibal"),
                            ("idpay", "IDPay"),
                        ],
                        default="zarinpal",
                        max_length=20,
                    ),
                ),
                (
                    "fallback_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of gateway names to try if the active gateway's request fails, e.g. ['zibal', 'idpay'].",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
